# 端口
server:
  port: 20705

spring:
#  application:
#    name: order-server

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true


# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true