# 端口
server:
  port: 20705

spring:
#  application:
#    name: order-server


# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true


logging:
  level:
    root: debug
  path: /data/logs


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
